name: "Get & cache dependencies"
description: "An action to get and cache dependencies for a Node.js project"
inputs:
  node-version:
    description: "The Node.js version to install"
    required: false
    default: "18"
outputs:
  node-version:
    description: "The Node.js version that was installed"
    value: "${{ steps.install-deps.outputs.nodeversion }}"
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      id: install-deps
      working-directory: ./second-action
      run: |
        npm ci
        echo "nodeversion='${{ inputs.node-version }}'" >> $GITHUB_OUTPUT
      shell: bash
